import { BasketInterface, Category, ProductInterface, ProductsListInterface } from '../types';

export const allProductsDefault: ProductsListInterface[] = [
  {
    id: '123',
    category: Category.tea,
    type: ['czarna', 'earl grey'],
    name: 'Earl Grey Rainbow',
    image: 'eargreyrainbow.webp',
    price: 10.99,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '124',
    category: Category.tea,
    type: ['owocowa'],
    name: 'Wiśnia i Rum',
    image: 'wiśniairum.webp',
    price: 9.95,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: 9.45,
    new: null,
    state:8000,
  },
  {
    id: '125',
    category: Category.coffee,
    type: ['smakowa'],
    name: 'Kawa Snickers',
    image: 'kawasnickers.webp',
    price: 11.70,
    numberOfUnits: 100,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '126',
    category: Category.tea,
    type: ['zielona'],
    name: 'Duch Poranka',
    image: 'duchporanka.webp',
    price: 9.39,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '127',
    category: Category.coffee,
    type: ['smakowa'],
    name: 'Pomarańcza w czekoladzie',
    image: 'pomaranczawczekoladzie.webp',
    price: 11.70,
    numberOfUnits: 100,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '128',
    category: Category.tea,
    type: ['owocowa'],
    name: 'Łyk Szczęścia',
    image: 'łykszczęścia.webp',
    price: 9.90,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '129',
    category: Category.tea,
    type: ['owocowa'],
    name: 'Mango Tango Super Owocowa',
    image: 'mangotangosuperowocowa.webp',
    price: 11.10,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '130',
    category: Category.tea,
    type: ['specjalna'],
    name: 'Odporność',
    image: 'odporność.webp',
    price: 9.90,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: 1,
    state:8000,
  },
  {
    id: '131',
    category: Category.tea,
    type: ['specjalna'],
    name: 'Samo Zdrowie',
    image: 'samozdrowie.webp',
    price: 11.10,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: 9.99,
    new: null,
    state:8000,
  },
  {
    id: '132',
    category: Category.coffee,
    type: ['smakowa'],
    name: 'Irish Whisky',
    image: 'irishwhisky.webp',
    price: 11.70,
    numberOfUnits: 100,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '133',
    category: Category.accessories,
    type: ['zaparzaczei filtry do herbaty'],
    name: 'Zaparzacz do herbaty silikonowy SILICO TRUSKAWKA',
    image: 'zaparzaczdoherbatysilikonowysilicotruskawka.webp',
    price: 10.90,
    numberOfUnits: 1,
    unit: 'szt',
    forGift: null,
    promo: null,
    new: null,
    state:8000,
  },
  {
    id: '134',
    category: Category.tea,
    type: ['kwitnąca'],
    name: 'Kwitnąca bombonierka - Czarna',
    image: 'kwitnącabombonierka-czarna.webp',
    price: 55.90,
    numberOfUnits: 1,
    unit: 'szt',
    forGift: 1,
    promo: null,
    new: null,
    state:15,
  },
];

export const exemplaryProduct: ProductInterface = {
  id: '123',
  name: 'Earl Grey Rainbow',
  category: Category.tea,
  type: ['czarna', 'earl grey'],
  image: 'eargreyrainbow.webp',
  price: 10.99,
  promo: null,
  numberOfUnits: 50,
  unit: 'g',
  state: 8000,
  forGift: null,
  onHomePage: 1,
  new: null,
  description: 'Herbata Earl Grey Rainbow to barwna i smaczna czarna herbata o wyjątkowym, owocowym i przyjemnym smaku i aromacie. Niezwykłe walory smakowe i aromatyczne są zasługą bławatka, szafranu, płatków słonecznika i róży. Herbata wyjątkowa w smaku o nietuzinkowym wyglądzie. Polecana sympatykom Earl Grey’a.',
  ingredients: 'Herbata czarna, bławatek, nagietek, dziki szafran, płatki róży, aromat',
  countryOrigin: 'Sri Lanka',
  amountBrew: 'pół łyżeczki / filiżanka',
  temperatureBrew: '95',
  timeBrew: '2-3 min',
  numberBrews: 'raz',
  wayStore: 'Przechowywać w zamkniętym opakowaniu, w suchym i chłodnym miejscu',
  coffeeSpecies: null,
  howToBrew: null,
  size: null,
};

export const productDefault: ProductInterface = {
  id: '',
  name: '',
  category: Category.tea,
  type: [],
  image: '',
  price: 0,
  promo: null,
  numberOfUnits: 50,
  unit: 'g',
  state: 0,
  forGift: null,
  onHomePage: null,
  new: null,
  description: '',
  ingredients: '',
  countryOrigin: '',
  amountBrew: '',
  temperatureBrew: '',
  timeBrew: '',
  numberBrews: '',
  wayStore: '',
  coffeeSpecies: null,
  howToBrew: null,
  size: null,
};

export const exemplaryProductInBasket: BasketInterface = {
  id: '123',
  name: 'Earl Grey Rainbow',
  category:Category.tea,
  type: ['czarna', 'earl grey',],
  image: 'eargreyrainbow.webp',
  price: 10.99,
  numberOfUnits: 50,
  unit: 'g',
  state: 4000,
};


export const oneProductInBasketDefault: BasketInterface = {
  id: '',
  name: '',
  category:Category.tea,
  type: [],
  image: '',
  price: 0,
  numberOfUnits: 0,
  unit: 'g',
  state: 0,
};