import { Category, ProductsListInterface } from '../types';

export const allProductsDefault: ProductsListInterface[] = [
  {
    id: '123',
    category: Category.tea,
    type: ['czarna', 'earl grey'],
    name: 'Earl Grey Rainbow',
    image: 'eargreyrainbow.webp',
    price: 10.99,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '124',
    category: Category.tea,
    type: ['owocowa'],
    name: 'Wiśnia i Rum',
    image: 'wiśniairum.webp',
    price: 9.95,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: 9.45,
    new: null,
  },
  {
    id: '125',
    category: Category.coffee,
    type: ['smakowa'],
    name: 'Kawa Snickers',
    image: 'kawasnickers.webp',
    price: 11.70,
    numberOfUnits: 100,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '126',
    category: Category.tea,
    type: ['zielona'],
    name: 'Duch Poranka',
    image: 'duchporanka.webp',
    price: 9.39,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '127',
    category: Category.coffee,
    type: ['smakowa'],
    name: 'Pomarańcza w czekoladzie',
    image: 'pomaranczawczekoladzie.webp',
    price: 11.70,
    numberOfUnits: 100,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '128',
    category: Category.tea,
    type: ['owocowa'],
    name: 'Łyk Szczęścia',
    image: 'łykszczęścia.webp',
    price: 9.90,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '129',
    category: Category.tea,
    type: ['owocowa'],
    name: 'Mango Tango Super Owocowa',
    image: 'mangotangosuperowocowa.webp',
    price: 11.10,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '130',
    category: Category.tea,
    type: ['specjalna'],
    name: 'Odporność',
    image: 'odporność.webp',
    price: 9.90,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: null,
    new: 1,
  },
  {
    id: '131',
    category: Category.tea,
    type: ['specjalna'],
    name: 'Samo Zdrowie',
    image: 'samozdrowie.webp',
    price: 11.10,
    numberOfUnits: 50,
    unit: 'g',
    forGift: null,
    promo: 9.99,
    new: null,
  },
  {
    id: '132',
    category: Category.coffee,
    type: ['smakowa'],
    name: 'Irish Whisky',
    image: 'irishwhisky.webp',
    price: 11.70,
    numberOfUnits: 100,
    unit: 'g',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '133',
    category: Category.accessories,
    type: null,
    name: 'Zaparzacz do herbaty silikonowy SILICO TRUSKAWKA',
    image: 'zaparzaczdoherbatysilikonowysilicotruskawka.webp',
    price: 10.90,
    numberOfUnits: 1,
    unit: 'szt',
    forGift: null,
    promo: null,
    new: null,
  },
  {
    id: '134',
    category: Category.tea,
    type: ['kwitnąca'],
    name: 'Kwitnąca bombonierka - Czarna',
    image: 'kwitnącabombonierka-czarna.webp',
    price: 55.90,
    numberOfUnits: 1,
    unit: 'szt',
    forGift: 1,
    promo: null,
    new: null,
  },
];