import {
  ProfileUserDataType,
  UserInterface,
  UserRegistrationDataType,
} from '../types';

export const defaultUser: UserInterface = {
  id: '',
  role: '',
  email: '',
  accountType: 'Paragon',
  password: '',
  name: '',
  surName: '',
  companyName: '',
  nip: '',
  street: '',
  homeNumber: '',
  postCode: '',
  city: '',
  phone: '',
  delivery: {
    deliveryName: '',
    deliverySurName: '',
    deliveryCompanyName: '',
    deliveryStreet: '',
    deliveryHomeNumber: '',
    deliveryPostCode: '',
    deliveryCity: '',
  },
};

export const defaultUserProfile: ProfileUserDataType = {
  id: '',
  email: '',
  accountType: 'Paragon',
  name: '',
  surName: '',
  companyName: '',
  nip: '',
  street: '',
  homeNumber: '',
  postCode: '',
  city: '',
  phone: '',
  delivery: {
    deliveryName: '',
    deliverySurName: '',
    deliveryCompanyName: '',
    deliveryStreet: '',
    deliveryHomeNumber: '',
    deliveryPostCode: '',
    deliveryCity: '',
  },
};

export const defaultUserRegister: UserRegistrationDataType = {
  id: '',
  email: '',
  password:'',
  accountType:'Paragon',
  name: '',
  surName: '',
  companyName: '',
  nip: '',
  street: '',
  homeNumber: '',
  postCode: '',
  city: '',
  phone: '',
  delivery: {
    deliveryName: '',
    deliverySurName: '',
    deliveryCompanyName: '',
    deliveryStreet: '',
    deliveryHomeNumber: '',
    deliveryPostCode: '',
    deliveryCity: '',
  },
};

export const defaultUserActive: UserInterface = {
  id: '123',
  role: 'user',
  email: 'rafal@gmail.com',
  password: 'brpio3t89hgehugh87sehiuh',
  accountType: 'Paragon',
  name: 'Rafał',
  surName: 'Matraś',
  companyName: '',
  nip: '',
  street: 'Nowodworska 29b',
  homeNumber: '103',
  postCode: '03-140',
  city: 'Warszawa',
  phone: '606 455 202',
  delivery: {
    deliveryName: '',
    deliverySurName: '',
    deliveryCompanyName: '',
    deliveryStreet: '',
    deliveryHomeNumber: '',
    deliveryPostCode: '',
    deliveryCity: '',
  },
};